%% Declare RenderToolbox3 version 3 toolbox configuration.
%
% This script generates a JSON file which allows the Toolbox Toolbox to
% automatically install RenderToolbox3.
%
% 2016 benjamin.heasly@gmail.com

config = [ ...
    tbToolboxRecord( ...
    'name', 'mitsuba-spectral-docker', ...
    'type', 'docker', ...
    'url', 'ninjaben/mitsuba-spectral'), ...
    tbToolboxRecord( ...
    'name', 'mMitsuba', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/mMitsuba.git'), ...
    tbToolboxRecord( ...
    'name', 'pbrt-v2-spectral-docker', ...
    'type', 'docker', ...
    'url', 'ninjaben/pbrt-v2-spectral-docker'), ...
    tbToolboxRecord( ...
    'name', 'mPbrt', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/mPbrt.git'), ...
    tbToolboxRecord( ...
    'name', 'mexximp_binary', ...
    'type', 'webget', ...
    'url', 'https://github.com/RenderToolbox3/mexximp/releases/download/v0.1.1/build.zip'), ...
    tbToolboxRecord( ...
    'name', 'mexximp', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/mexximp.git'), ...
    tbToolboxRecord( ...
    'name', 'SphereRendererToolbox', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/SphereRendererToolbox.git'), ...
    tbToolboxRecord( ...
    'name', 'Psychtoolbox', ...
    'type', 'git', ...
    'url', 'https://github.com/Psychtoolbox-3/Psychtoolbox-3.git', ...
    'subfolder', 'Psychtoolbox'), ...
    tbToolboxRecord( ...
    'name', 'RenderToolbox3_binary', ...
    'type', 'webget', ...
    'url', 'https://github.com/RenderToolbox3/RenderToolbox3/releases/download/test-build-2/build.zip'), ...
    tbToolboxRecord( ...
    'name', 'RenderToolbox3', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/RenderToolbox3.git', ...
    'flavor', 'version3', ...
    'localHookTemplate', 'rtbLocalConfigTemplate.m'), ...
    ];

pathHere = fileparts(mfilename('fullpath'));
configFile = fullfile(pathHere, 'rtbToolboxConfig.json');
tbWriteConfig(config, 'configPath', configFile);
